# Redocly Realm configuration for multi-page documentation site
apis:
  webrobot-etl-api@v1:
    root: openapi.yaml

# Docs configuration for multi-page documentation
docs:
  root: index.md
  sidebars: sidebars.yaml
  # Explicitly set index.md as home page (no redirect)
  homePage: index.md

# Theme configuration
theme:
  openapi:
    generateCodeSamples:
      languages:
        - lang: curl
        - lang: Python
        - lang: JavaScript

# Disable search plugin completely
# The search plugin checks for r.search?.hide
search:
  hide: true

