# Redocly Realm configuration for multi-page documentation site
apis:
  webrobot-etl-api@v1:
    root: openapi.yaml

# Docs configuration for multi-page documentation
docs:
  root: index.md
  sidebars: sidebars.yaml

# Explicit redirects configuration
# Force root to point to index.md instead of auto-redirecting to first page
redirects:
  '/': '/index'

# Theme configuration
theme:
  openapi:
    generateCodeSamples:
      languages:
        - lang: curl
        - lang: Python
        - lang: JavaScript

# Disable search plugin completely
# The search plugin checks for r.search?.hide
search:
  hide: true

