# Redocly Realm configuration for multi-page documentation site
apis:
  webrobot-etl-api@v1:
    root: openapi.yaml

# Docs configuration for multi-page documentation
docs:
  # Docs content root directory (all markdown lives under repo root: index.md, guides/, it/, ...)
  root: .
  # Explicit homepage (otherwise Realm may choose the first sidebar page)
  homePage: index.md
  sidebars: sidebars.yaml

# Explicit redirects configuration
# Note: index.md is served at `/` (there is no `/index` route).
redirects:
  '/it': '/it/index'
  '/el': '/el/index'

# Theme configuration
theme:
  openapi:
    generateCodeSamples:
      languages:
        - lang: curl
        - lang: Python
        - lang: JavaScript

# Disable search plugin completely
# The search plugin checks for r.search?.hide
search:
  hide: true

