# Concrete example: Surebet detection using intelligent navigation and extraction
# This pipeline uses intelligent_explore and intelligent_flatSelect to extract odds
# from bookmaker sites with complex, non-trivial table structures.

fetch:
  url: "https://www.bet365.com/football"
  traces:
    - { action: "visit", params: { url: "https://www.bet365.com/football", cooldown: 1.0 } }
    - { action: "wait", params: { seconds: 2 } }  # Wait for dynamic content to load

pipeline:
  # ============================================
  # Step 1: Intelligent Navigation
  # Navigate through match/event pages using LLM to find links
  # ============================================
  - stage: intelligent_explore
    args: 
      - "links to football match pages or event listings"  # Segmentation prompt
      - 3  # Depth: navigate 3 levels deep

  # ============================================
  # Step 2: Intelligent Table Extraction
  # Extract odds from complex table structures using LLM
  # ============================================
  - stage: intelligent_flatSelect
    args:
      # Segmentation prompt: Find repeated elements (rows/cards) containing betting markets
      - "repeated betting market rows or cards, each containing a market type and multiple selection options with odds"
      # Extraction prompt: Extract structured data from each segment
      - "Extract: event_name (match/event title), event_date (date/time), market_type (e.g., match_winner, over_under, handicap), selection (e.g., home_win, away_win, draw, over_2.5, under_2.5), odds_decimal (decimal odds as number), odds_raw (original odds string)"
      # Optional prefix for extracted fields
      - "bet365_"  # Prefix for all extracted fields

  # ============================================
  # Step 3: Normalize and Enrich
  # ============================================
  - stage: python_row_transform:normalize_bet365_intelligent
    args: []
  - stage: python_row_transform:add_metadata
    args:
      - bookmaker: "bet365"
        sport: "football"
        extraction_method: "intelligent"

  # ============================================
  # Step 4: Cache and Store
  # ============================================
  - stage: cache
    args: []
  - stage: store
    args: [ "bet365_offers" ]

  # ============================================
  # Bookmaker 2: Pinnacle
  # ============================================
  - stage: reset
    args: []
  - stage: visit
    args: [ "https://www.pinnacle.com/en/football" ]
  - stage: intelligent_explore
    args:
      - "links to football match pages"
      - 2
  - stage: intelligent_flatSelect
    args:
      - "betting market sections with odds for different selections"
      - "Extract: event_name, event_date, market_type, selection, odds_decimal, odds_raw"
      - "pinnacle_"
  - stage: python_row_transform:normalize_pinnacle_intelligent
    args: []
  - stage: python_row_transform:add_metadata
    args:
      - bookmaker: "pinnacle"
        sport: "football"
        extraction_method: "intelligent"
  - stage: cache
    args: []
  - stage: store
    args: [ "pinnacle_offers" ]

  # ============================================
  # Bookmaker 3: Betfair
  # ============================================
  - stage: reset
    args: []
  - stage: visit
    args: [ "https://www.betfair.com/sport/football" ]
  - stage: intelligent_explore
    args:
      - "event or match links in the football section"
      - 2
  - stage: intelligent_flatSelect
    args:
      - "betting market rows or cards with selection buttons and odds"
      - "Extract: event_name, event_date, market_type, selection, odds_decimal, odds_raw"
      - "betfair_"
  - stage: python_row_transform:normalize_betfair_intelligent
    args: []
  - stage: python_row_transform:add_metadata
    args:
      - bookmaker: "betfair"
        sport: "football"
        extraction_method: "intelligent"
  - stage: cache
    args: []
  - stage: store
    args: [ "betfair_offers" ]

  # ============================================
  # Bookmaker 4: William Hill
  # ============================================
  - stage: reset
    args: []
  - stage: visit
    args: [ "https://sports.williamhill.com/betting/en-gb/football" ]
  - stage: intelligent_explore
    args:
      - "football match or event links"
      - 2
  - stage: intelligent_flatSelect
    args:
      - "betting market containers with selection options and price buttons"
      - "Extract: event_name, event_date, market_type, selection, odds_decimal, odds_raw"
      - "williamhill_"
  - stage: python_row_transform:normalize_williamhill_intelligent
    args: []
  - stage: python_row_transform:add_metadata
    args:
      - bookmaker: "williamhill"
        sport: "football"
        extraction_method: "intelligent"
  - stage: cache
    args: []
  - stage: store
    args: [ "williamhill_offers" ]

  # ============================================
  # Bookmaker 5: Unibet
  # ============================================
  - stage: reset
    args: []
  - stage: visit
    args: [ "https://www.unibet.com/betting/sports/filter/football" ]
  - stage: intelligent_explore
    args:
      - "football match links or event cards"
      - 2
  - stage: intelligent_flatSelect
    args:
      - "betting market sections with odds for different outcomes"
      - "Extract: event_name, event_date, market_type, selection, odds_decimal, odds_raw"
      - "unibet_"
  - stage: python_row_transform:normalize_unibet_intelligent
    args: []
  - stage: python_row_transform:add_metadata
    args:
      - bookmaker: "unibet"
        sport: "football"
        extraction_method: "intelligent"
  - stage: cache
    args: []
  - stage: store
    args: [ "unibet_offers" ]

  # ============================================
  # Step 5: Merge All Bookmakers
  # ============================================
  - stage: reset
    args: []
  - stage: union_with
    args: [ "bet365_offers", "pinnacle_offers", "betfair_offers", "williamhill_offers", "unibet_offers" ]

  # ============================================
  # Step 6: Generate Event ID for Matching
  # ============================================
  - stage: python_row_transform:generate_event_id
    args: []

  # ============================================
  # Step 7: Create Matching Table
  # Group by event_id + market_type + selection
  # ============================================
  - stage: python_row_transform:create_matching_key
    args: []

  # ============================================
  # Step 8: Detect Surebet Opportunities
  # ============================================
  - stage: python_row_transform:detect_surebet
    args:
      - min_profit_margin: 0.02  # Minimum 2% profit margin

  # ============================================
  # Step 9: Save Results
  # ============================================
  - stage: save_csv
    args: [ "${OUTPUT_PATH_SUREBET_OPPORTUNITIES}", "overwrite" ]

