# Concrete example: Build instruction-following dataset for LLM fine-tuning (No-CC policy)
#
# This example is designed to avoid Creative Commons-licensed sources.
# Use ONLY sources that are:
# - customer-owned/internal, or
# - public domain, or
# - explicitly permissive-licensed (non-CC) with redistribution/training rights.
#
# Notes:
# - WebRobot ETL does not automatically validate licenses.
# - You should maintain an allowlist and store per-record provenance + license metadata.

fetch:
  # Customer-owned documentation portal or knowledge base (recommended)
  url: "${INTERNAL_DOCS_START_URL}"

pipeline:
  # ============================================
  # Source 1: Customer-owned documentation (crawl)
  # ============================================
  - stage: explore
    args: [ "a", 2 ]
  - stage: join
    args: [ "a", "LeftOuter" ]
  - stage: extract
    args:
      - { selector: "title", method: "text", as: "title" }
      - { selector: "body", method: "text", as: "content" }
      - { selector: "link[rel=canonical]", method: "attr:href", as: "url" }
  - stage: python_row_transform:normalize_owned_docs
    args: []
  - stage: python_row_transform:convert_to_instruction_format
    args:
      - format: "instruction_following"
      - instruction_field: "title"
      - output_field: "content"
  - stage: python_row_transform:add_metadata
    args:
      - source: "internal"
        domain: "customer_docs"
        license: "customer_owned"
        format: "instruction_following"
  - stage: cache
    args: []
  - stage: store
    args: [ "owned_docs_dataset" ]

  # ============================================
  # Source 2: Public domain documents (pre-curated CSV)
  # ============================================
  - stage: reset
    args: []
  - stage: load_csv
    args:
      - { path: "${PUBLIC_DOMAIN_DOCS_CSV_PATH}", header: "true", inferSchema: "true" }
  - stage: python_row_transform:normalize_public_domain_docs
    args: []
  - stage: python_row_transform:convert_to_instruction_format
    args:
      - format: "instruction_following"
      - instruction_field: "doc_title"
      - output_field: "doc_text"
  - stage: python_row_transform:add_metadata
    args:
      - source: "public_domain"
        domain: "public_docs"
        license: "public_domain"
        format: "instruction_following"
  - stage: cache
    args: []
  - stage: store
    args: [ "public_domain_dataset" ]

  # ============================================
  # Source 3: Permissive-licensed code/docs (pre-curated CSV)
  # ============================================
  - stage: reset
    args: []
  - stage: load_csv
    args:
      - { path: "${PERMISSIVE_CODE_DOCS_CSV_PATH}", header: "true", inferSchema: "true" }
  - stage: python_row_transform:normalize_permissive_code_docs
    args: []
  - stage: python_row_transform:convert_to_instruction_format
    args:
      - format: "instruction_following"
      - instruction_field: "title"
      - output_field: "content"
  - stage: python_row_transform:add_metadata
    args:
      - source: "permissive_code_docs"
        domain: "code_docs"
        license: "permissive_non_cc"
        format: "instruction_following"
  - stage: cache
    args: []
  - stage: store
    args: [ "permissive_code_docs_dataset" ]

  # ============================================
  # Merge: Union all sources
  # ============================================
  - stage: reset
    args: []
  - stage: union_with
    args: [ "owned_docs_dataset", "public_domain_dataset", "permissive_code_docs_dataset" ]

  # ============================================
  # Clean, normalize, deduplicate
  # ============================================
  - stage: python_row_transform:clean_text
    args: []
  - stage: python_row_transform:normalize_text
    args: []
  - stage: python_row_transform:generate_text_hash
    args: []
  - stage: dedup
    args: [ "text_hash" ]

  # ============================================
  # Save dataset (CSV)
  # ============================================
  - stage: save_csv
    args: [ "${OUTPUT_PATH_DATASET_CSV}", "overwrite" ]

